[package]
name = "state_store"
version = "0.1.0"
edition = "2021"
description = "Custom KV store implementation"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true } 