[package]
name = "aria_runtime"
version = "0.1.0"
edition = "2021"
description = "Core Aria runtime"

[dependencies]
tokio = { workspace = true }
tokio-stream = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# Internal crypto for signatures
blake3 = { workspace = true } 