[package]
name = "hostfx"
version = "0.1.0"
edition = "2021"
description = "Host function interfaces (LLM, GPU, network, I/O)"
 
[dependencies]
aria_runtime = { path = "../aria_runtime" }
reqwest = { workspace = true }
serde_json = { workspace = true } 